source("main_func.R")

binance_func <- function(finish_table, lim_or_mark, data_market_price){
  # заполнение курсов binance
  get_price_binance <- function(Name_crypt1, Name_crypt2, Name_crypt3, table_Crypto, lim_or_mark, data_market_price){
    # преобразуем list в data.frame
    data <- as.data.frame(do.call(rbind, data_market_price))
    
    switch(lim_or_mark, 
           lim={
             # заполняем строчку курсов для limit price
             # при прямой --------------------------------------------------
             table_Crypto[1,2] <- as.numeric(data[data[,1]==Name_crypt1,"bidPrice"])
             table_Crypto[1,3] <- as.numeric(data[data[,1]==Name_crypt2,"bidPrice"])
             table_Crypto[1,4] <- 1/(as.numeric(data[data[,1]==Name_crypt3,"askPrice"]))
             table_Crypto[1,10] <- 1/(as.numeric(data[data[,1]==Name_crypt1,"askPrice"]))
             table_Crypto[1,11] <- as.numeric(data[data[,1]==Name_crypt3,"bidPrice"])
             table_Crypto[1,12] <- 1/(as.numeric(data[data[,1]==Name_crypt2,"askPrice"]))
             # при обратной ------------------------------------------------
             table_Crypto[1,6] <- as.numeric(data[data[,1]==Name_crypt3,"bidPrice"])
             table_Crypto[1,7] <- 1/(as.numeric(data[data[,1]==Name_crypt2,"askPrice"]))
             table_Crypto[1,8] <- 1/(as.numeric(data[data[,1]==Name_crypt1,"askPrice"]))
             table_Crypto[1,14] <- as.numeric(data[data[,1]==Name_crypt2,"bidPrice"])
             table_Crypto[1,15] <- 1/(as.numeric(data[data[,1]==Name_crypt3,"askPrice"]))
             table_Crypto[1,16] <- as.numeric(data[data[,1]==Name_crypt1,"bidPrice"])
           },
           mark={
             # заполняем строчку курсов для market price
             # при прямой --------------------------------------------------
             table_Crypto[1,2] <- as.numeric(data[data[,1]==Name_crypt1,"lastPrice"])
             table_Crypto[1,3] <- as.numeric(data[data[,1]==Name_crypt2,"lastPrice"])
             table_Crypto[1,4] <- 1/(as.numeric(data[data[,1]==Name_crypt3,"lastPrice"]))
             table_Crypto[1,10] <- 1/(as.numeric(data[data[,1]==Name_crypt1,"lastPrice"]))
             table_Crypto[1,11] <- as.numeric(data[data[,1]==Name_crypt3,"lastPrice"])
             table_Crypto[1,12] <- 1/(as.numeric(data[data[,1]==Name_crypt2,"lastPrice"]))
             # при обратной ------------------------------------------------
             table_Crypto[1,6] <- as.numeric(data[data[,1]==Name_crypt3,"lastPrice"])
             table_Crypto[1,7] <- 1/(as.numeric(data[data[,1]==Name_crypt2,"lastPrice"]))
             table_Crypto[1,8] <- 1/(as.numeric(data[data[,1]==Name_crypt1,"lastPrice"]))
             table_Crypto[1,14] <- as.numeric(data[data[,1]==Name_crypt2,"lastPrice"])
             table_Crypto[1,15] <- 1/(as.numeric(data[data[,1]==Name_crypt3,"lastPrice"]))
             table_Crypto[1,16] <- as.numeric(data[data[,1]==Name_crypt1,"lastPrice"])
           })
    # ------------------
    return(table_Crypto)
  }
  
  # -----------------------------------------------------------------------------------
  # узнать номер криптовалютной пары для первых 3 параметров в нижних функциях
  #what_num_crypt<-as.data.frame.raw(data_market_price)
  #View(what_num_crypt)
  
  # заполняем значение курса
  table_ADA_USDT <- get_price_binance("ADABTC", "BTCUSDT", "ADAUSDT", table_ADA_USDT, lim_or_mark, data_market_price)
  table_ADA_ETH <- get_price_binance("ADAETH", "ETHBTC", "ADABTC", table_ADA_ETH, lim_or_mark, data_market_price)
  table_BNB_USDT <- get_price_binance("BNBBTC", "BTCUSDT", "BNBUSDT", table_BNB_USDT, lim_or_mark, data_market_price)
  table_BNB_ETH <- get_price_binance("BNBETH", "ETHBTC", "BNBBTC", table_BNB_ETH, lim_or_mark, data_market_price) 
  table_BTG_ETH <- get_price_binance("BTGETH", "ETHBTC", "BTGBTC", table_BTG_ETH, lim_or_mark, data_market_price)
  table_DASH_ETH <- get_price_binance("DASHETH", "ETHBTC", "DASHBTC", table_DASH_ETH, lim_or_mark, data_market_price)
  table_EOS_USDT <- get_price_binance("EOSBTC", "BTCUSDT", "EOSUSDT", table_EOS_USDT, lim_or_mark, data_market_price)
  table_EOS_ETH <- get_price_binance("EOSETH", "ETHBTC", "EOSBTC", table_EOS_ETH, lim_or_mark, data_market_price) 
  table_ETC_USDT <- get_price_binance("ETCBTC", "BTCUSDT", "ETCUSDT", table_ETC_USDT, lim_or_mark, data_market_price) 
  table_ETC_ETH <- get_price_binance("ETCETH", "ETHBTC", "ETCBTC", table_ETC_ETH, lim_or_mark, data_market_price)
  table_ETH_USDT <- get_price_binance("ETHBTC", "BTCUSDT", "ETHUSDT", table_ETH_USDT, lim_or_mark, data_market_price) 
  table_GNT_ETH <- get_price_binance("GNTETH", "ETHBTC", "GNTBTC", table_GNT_ETH, lim_or_mark, data_market_price)
  table_ICX_USDT <- get_price_binance("ICXBTC", "BTCUSDT", "ICXUSDT", table_ICX_USDT, lim_or_mark, data_market_price) 
  table_ICX_ETH <- get_price_binance("ICXETH", "ETHBTC", "ICXBTC", table_ICX_ETH, lim_or_mark, data_market_price) 
  table_IOTA_USDT <- get_price_binance("IOTABTC", "BTCUSDT", "IOTAUSDT", table_IOTA_USDT, lim_or_mark, data_market_price)
  table_IOTA_ETH <- get_price_binance("IOTAETH", "ETHBTC", "IOTABTC", table_IOTA_ETH, lim_or_mark, data_market_price) 
  table_LSK_ETH <- get_price_binance("LSKETH", "ETHBTC", "LSKBTC", table_LSK_ETH, lim_or_mark, data_market_price) 
  table_LTC_USDT <- get_price_binance("LTCBTC", "BTCUSDT", "LTCUSDT", table_LTC_USDT, lim_or_mark, data_market_price) 
  table_LTC_ETH <- get_price_binance("LTCETH", "ETHBTC", "LTCBTC", table_LTC_ETH, lim_or_mark, data_market_price) 
  table_NANO_ETH <- get_price_binance("NANOETH", "ETHBTC", "NANOBTC", table_NANO_ETH, lim_or_mark, data_market_price) 
  table_NEO_USDT <- get_price_binance("NEOBTC", "BTCUSDT", "NEOUSDT", table_NEO_USDT, lim_or_mark, data_market_price)
  table_NEO_ETH <- get_price_binance("NEOETH", "ETHBTC", "NEOBTC", table_NEO_ETH, lim_or_mark, data_market_price) 
  table_OMG_ETH <- get_price_binance("OMGETH", "ETHBTC", "OMGBTC", table_OMG_ETH, lim_or_mark, data_market_price)
  table_ONT_USDT <- get_price_binance("ONTBTC", "BTCUSDT", "ONTUSDT", table_ONT_USDT, lim_or_mark, data_market_price)
  table_ONT_ETH <- get_price_binance("ONTETH", "ETHBTC", "ONTBTC", table_ONT_ETH, lim_or_mark, data_market_price)
  table_QTUM_USDT <- get_price_binance("QTUMBTC", "BTCUSDT", "QTUMUSDT", table_QTUM_USDT, lim_or_mark, data_market_price)
  table_QTUM_ETH <- get_price_binance("QTUMETH", "ETHBTC", "QTUMBTC", table_QTUM_ETH, lim_or_mark, data_market_price)
  table_SNT_ETH <- get_price_binance("SNTETH", "ETHBTC", "SNTBTC", table_SNT_ETH, lim_or_mark, data_market_price) 
  table_STRAT_ETH <- get_price_binance("STRATETH", "ETHBTC", "STRATBTC", table_STRAT_ETH, lim_or_mark, data_market_price)
  table_TRX_USDT <- get_price_binance("TRXBTC", "BTCUSDT", "TRXUSDT", table_TRX_USDT, lim_or_mark, data_market_price) 
  table_TRX_ETH <- get_price_binance("TRXETH", "ETHBTC", "TRXBTC", table_TRX_ETH, lim_or_mark, data_market_price) 
  table_VET_USDT <- get_price_binance("VETBTC", "BTCUSDT", "VETUSDT", table_VET_USDT, lim_or_mark, data_market_price)
  table_VET_ETH <- get_price_binance("VETETH", "ETHBTC", "VETBTC", table_VET_ETH, lim_or_mark, data_market_price) 
  table_WAVES_ETH <- get_price_binance("WAVESETH", "ETHBTC", "WAVESBTC", table_WAVES_ETH, lim_or_mark, data_market_price)
  table_XEM_ETH <- get_price_binance("XEMETH", "ETHBTC", "XEMBTC", table_XEM_ETH, lim_or_mark, data_market_price)
  table_XLM_USDT <- get_price_binance("XLMBTC", "BTCUSDT", "XLMUSDT", table_XLM_USDT, lim_or_mark, data_market_price)
  table_XLM_ETH <- get_price_binance("XLMETH", "ETHBTC", "XLMBTC", table_XLM_ETH, lim_or_mark, data_market_price) 
  table_XMR_ETH <- get_price_binance("XMRETH", "ETHBTC", "XMRBTC", table_XMR_ETH, lim_or_mark, data_market_price)
  table_XRP_USDT <- get_price_binance("XRPBTC", "BTCUSDT", "XRPUSDT", table_XRP_USDT, lim_or_mark, data_market_price)
  table_XRP_ETH <- get_price_binance("XRPETH", "ETHBTC", "XRPBTC", table_XRP_ETH, lim_or_mark, data_market_price) 
  table_XVG_ETH <- get_price_binance("XVGETH", "ETHBTC", "XVGBTC", table_XVG_ETH, lim_or_mark, data_market_price)
  table_ZEC_ETH <- get_price_binance("ZECETH", "ETHBTC", "ZECBTC", table_ZEC_ETH, lim_or_mark, data_market_price)
  table_ZRX_ETH <- get_price_binance("ZRXETH", "ETHBTC", "ZRXBTC", table_ZRX_ETH, lim_or_mark, data_market_price)
  
  # -----------------------------------------------------------------------------------
  # выполняем расчет и заполняем строчки
  # https://api.binance.com/api/v1/exchangeInfo - тут смотрим делители, а именно колличество знаков после запятой (del1.1 - LOT_SIZE первой пары, del1.2 - PRICE_FILTER первой пары, del2.1 - LOT_SIZE второй пары, del2.2 - PRICE_FILTER второй пары, del3.1 - LOT_SIZE третьей пары, del3.2 - PRICE_FILTER третьей пары)
  table_ADA_USDT <- find_balance(table_ADA_USDT, ADA, BTC, binance_fee, 0, 8, 6, 2, 1, 5)
  table_ADA_ETH <- find_balance(table_ADA_ETH, ADA, ETH, binance_fee, 0, 8, 3, 6, 0, 8)
  table_BNB_USDT <- find_balance(table_BNB_USDT, BNB, BTC, binance_fee, 2, 6, 6, 2, 2, 4)
  table_BNB_ETH <- find_balance(table_BNB_ETH, BNB, ETH, binance_fee, 2, 6, 3, 6, 2, 6)
  table_BTG_ETH <- find_balance(table_BTG_ETH, BTG, ETH, binance_fee, 2, 6, 3, 6, 2, 5)
  table_DASH_ETH <- find_balance(table_DASH_ETH, DASH, ETH, binance_fee, 3, 5, 3, 6, 3, 6)
  table_EOS_USDT <- find_balance(table_EOS_USDT, EOS, BTC, binance_fee, 2, 7, 6, 2, 2, 4)
  table_EOS_ETH <- find_balance(table_EOS_ETH, EOS, ETH, binance_fee, 2, 6, 3, 6, 2, 7)
  table_ETC_USDT <- find_balance(table_ETC_USDT, ETC, BTC, binance_fee, 2, 5, 6, 2, 2, 4)
  table_ETC_ETH <- find_balance(table_ETC_ETH, ETC, ETH, binance_fee, 2, 5, 3, 6, 2, 6)
  table_ETH_USDT <- find_balance(table_ETH_USDT, ETH, BTC, binance_fee, 3, 6, 6, 2, 5, 2)
  table_GNT_ETH <- find_balance(table_GNT_ETH, GNT, ETH, binance_fee, 0, 8, 3, 6, 0, 8)
  table_ICX_USDT <- find_balance(table_ICX_USDT, ICX, BTC, binance_fee, 2, 7, 6, 2, 2, 4)
  table_ICX_ETH <- find_balance(table_ICX_ETH, ICX, ETH, binance_fee, 2, 5, 3, 6, 2, 7)
  table_IOTA_USDT <- find_balance(table_IOTA_USDT, IOTA, BTC, binance_fee, 0, 8, 6, 2, 2, 3)
  table_IOTA_ETH <- find_balance(table_IOTA_ETH, IOTA, ETH, binance_fee, 0, 7, 3, 6, 0, 8)
  table_LSK_ETH <- find_balance(table_LSK_ETH, LSK, ETH, binance_fee, 2, 6, 3, 6, 2, 7)
  table_LTC_USDT <- find_balance(table_LTC_USDT, LTC, BTC, binance_fee, 2, 6, 6, 2, 5, 2)
  table_LTC_ETH <- find_balance(table_LTC_ETH, LTC, ETH, binance_fee, 3, 5, 3, 6, 2, 6)
  table_NANO_ETH <- find_balance(table_NANO_ETH, NANO, ETH, binance_fee, 2, 6, 3, 6, 2, 7)
  table_NEO_USDT <- find_balance(table_NEO_USDT, NEO, BTC, binance_fee, 2, 6, 6, 2, 3, 3)
  table_NEO_ETH <- find_balance(table_NEO_ETH, NEO, ETH, binance_fee, 2, 6, 3, 6, 2, 6)
  table_OMG_ETH <- find_balance(table_OMG_ETH, OMG, ETH, binance_fee, 2, 6, 3, 6, 2, 6)
  table_ONT_USDT <- find_balance(table_ONT_USDT, ONT, BTC, binance_fee, 2, 7, 6, 2, 3, 3)
  table_ONT_ETH <- find_balance(table_ONT_ETH, ONT, ETH, binance_fee, 2, 6, 3, 6, 2, 7)
  table_QTUM_USDT <- find_balance(table_QTUM_USDT, QTUM, BTC, binance_fee, 2, 6, 6, 2, 3, 3)
  table_QTUM_ETH <- find_balance(table_QTUM_ETH, QTUM, ETH, binance_fee, 2, 6, 3, 6, 2, 6)
  table_SNT_ETH <- find_balance(table_SNT_ETH, SNT, ETH, binance_fee, 0, 7, 3, 6, 0, 7)
  table_STRAT_ETH <- find_balance(table_STRAT_ETH, STRAT, ETH, binance_fee, 2, 6, 3, 6, 2, 7)
  table_TRX_USDT <- find_balance(table_TRX_USDT, TRX, BTC, binance_fee, 0, 8, 6, 2, 1, 5)
  table_TRX_ETH <- find_balance(table_TRX_ETH, TRX, ETH, binance_fee, 0, 8, 3, 6, 0, 8)
  table_VET_USDT <- find_balance(table_VET_USDT, VET, BTC, binance_fee, 0, 8, 6, 2, 1, 5)
  table_VET_ETH <- find_balance(table_VET_ETH, VET, ETH, binance_fee, 0, 8, 3, 6, 0, 8)
  table_WAVES_ETH <- find_balance(table_WAVES_ETH, WAVES, ETH, binance_fee, 2, 6, 3, 6, 2, 7)
  table_XEM_ETH <- find_balance(table_XEM_ETH, XEM, ETH, binance_fee, 0, 8, 3, 6, 0, 8)
  table_XLM_USDT <- find_balance(table_XLM_USDT, XLM, BTC, binance_fee, 0, 8, 6, 2, 1, 5)
  table_XLM_ETH <- find_balance(table_XLM_ETH, XLM, ETH, binance_fee, 0, 8, 3, 6, 0, 8)
  table_XMR_ETH <- find_balance(table_XMR_ETH, XMR, ETH, binance_fee, 3, 5, 3, 6, 3, 6)
  table_XRP_USDT <- find_balance(table_XRP_USDT, XRP, BTC, binance_fee, 0, 8, 6, 2, 1, 5)
  table_XRP_ETH <- find_balance(table_XRP_ETH, XRP, ETH, binance_fee, 0, 8, 3, 6, 0, 8)
  table_XVG_ETH <- find_balance(table_XVG_ETH, XVG, ETH, binance_fee, 0, 8, 3, 6, 0, 7)
  table_ZEC_ETH <- find_balance(table_ZEC_ETH, ZEC, ETH, binance_fee, 3, 5, 3, 6, 3, 5)
  table_ZRX_ETH <- find_balance(table_ZRX_ETH, ZRX, ETH, binance_fee, 0, 8, 3, 6, 0, 8)
  
  # -----------------------------------------------------------------------------------
  # готовим отчет
  finish_table <- find_result(finish_table, 1, table_ADA_USDT, ADA, BTC, "ADA->BTC->USDT->ADA", "ADA->USDT->BTC->ADA", "BTC->ADA->USDT->BTC", "BTC->USDT->ADA->BTC")
  finish_table <- find_result(finish_table, 2, table_ADA_ETH, ADA, ETH, "ADA->ETH->BTC->ADA", "ADA->BTC->ETH->ADA", "ETH->ADA->BTC->ETH", "ETH->BTC->ADA->ETH")
  finish_table <- find_result(finish_table, 3, table_BNB_USDT, BNB, BTC, "BNB->BTC->USDT->BNB", "BNB->USDT->BTC->BNB", "BTC->BNB->USDT->BTC", "BTC->USDT->BNB->BTC")
  finish_table <- find_result(finish_table, 4, table_BNB_ETH, BNB, ETH, "BNB->ETH->BTC->BNB", "BNB->BTC->ETH->BNB", "ETH->BNB->BTC->ETH", "ETH->BTC->BNB->ETH")
  finish_table <- find_result(finish_table, 5, table_BTG_ETH, BTG, ETH, "BTG->ETH->BTC->BTG", "BTG->BTC->ETH->BTG", "ETH->BTG->BTC->ETH", "ETH->BTC->BTG->ETH")
  finish_table <- find_result(finish_table, 6, table_DASH_ETH, DASH, ETH, "DASH->ETH->BTC->DASH", "DASH->BTC->ETH->DASH", "ETH->DASH->BTC->ETH", "ETH->BTC->DASH->ETH")
  finish_table <- find_result(finish_table, 7, table_EOS_USDT, EOS, BTC, "EOS->BTC->USDT->EOS", "EOS->USDT->BTC->EOS", "BTC->EOS->USDT->BTC", "BTC->USDT->EOS->BTC")
  finish_table <- find_result(finish_table, 8, table_EOS_ETH, EOS, ETH, "EOS->ETH->BTC->EOS", "EOS->BTC->ETH->EOS", "ETH->EOS->BTC->ETH", "ETH->BTC->EOS->ETH")
  finish_table <- find_result(finish_table, 9, table_ETC_USDT, ETC, BTC, "ETC->BTC->USDT->ETC", "ETC->USDT->BTC->ETC", "BTC->ETC->USDT->BTC", "BTC->USDT->ETC->BTC")
  finish_table <- find_result(finish_table, 10, table_ETC_ETH, ETC, ETH, "ETC->ETH->BTC->ETC", "ETC->BTC->ETH->ETC", "ETH->ETC->BTC->ETH", "ETH->BTC->ETC->ETH")
  finish_table <- find_result(finish_table, 11, table_ETH_USDT, ETH, BTC, "ETH->BTC->USDT->ETH", "ETH->USDT->BTC->ETH", "BTC->ETH->USDT->BTC", "BTC->USDT->ETH->BTC")
  finish_table <- find_result(finish_table, 12, table_GNT_ETH, GNT, ETH, "GNT->ETH->BTC->GNT", "GNT->BTC->ETH->GNT", "ETH->GNT->BTC->ETH", "ETH->BTC->GNT->ETH")
  finish_table <- find_result(finish_table, 13, table_ICX_USDT, ICX, BTC, "ICX->BTC->USDT->ICX", "ICX->USDT->BTC->ICX", "BTC->ICX->USDT->BTC", "BTC->USDT->ICX->BTC")
  finish_table <- find_result(finish_table, 14, table_ICX_ETH, ICX, ETH, "ICX->ETH->BTC->ICX", "ICX->BTC->ETH->ICX", "ETH->ICX->BTC->ETH", "ETH->BTC->ICX->ETH")
  finish_table <- find_result(finish_table, 15, table_IOTA_USDT, IOTA, BTC, "IOTA->BTC->USDT->IOTA", "IOTA->USDT->BTC->IOTA", "BTC->IOTA->USDT->BTC", "BTC->USDT->IOTA->BTC")
  finish_table <- find_result(finish_table, 16, table_IOTA_ETH, IOTA, ETH, "IOTA->ETH->BTC->IOTA", "IOTA->BTC->ETH->IOTA", "ETH->IOTA->BTC->ETH", "ETH->BTC->IOTA->ETH")
  finish_table <- find_result(finish_table, 17, table_LSK_ETH, LSK, ETH, "LSK->ETH->BTC->LSK", "LSK->BTC->ETH->LSK", "ETH->LSK->BTC->ETH", "ETH->BTC->LSK->ETH")
  finish_table <- find_result(finish_table, 18, table_LTC_USDT, LTC, BTC, "LTC->BTC->USDT->LTC", "LTC->USDT->BTC->LTC", "BTC->LTC->USDT->BTC", "BTC->USDT->LTC->BTC")
  finish_table <- find_result(finish_table, 19, table_LTC_ETH, LTC, ETH, "LTC->ETH->BTC->LTC", "LTC->BTC->ETH->LTC", "ETH->LTC->BTC->ETH", "ETH->BTC->LTC->ETH")
  finish_table <- find_result(finish_table, 20, table_NANO_ETH, NANO, ETH, "NANO->ETH->BTC->NANO", "NANO->BTC->ETH->NANO", "ETH->NANO->BTC->ETH", "ETH->BTC->NANO->ETH")
  finish_table <- find_result(finish_table, 21, table_NEO_USDT, NEO, BTC, "NEO->BTC->USDT->NEO", "NEO->USDT->BTC->NEO", "BTC->NEO->USDT->BTC", "BTC->USDT->NEO->BTC")
  finish_table <- find_result(finish_table, 22, table_NEO_ETH, NEO, ETH, "NEO->ETH->BTC->NEO", "NEO->BTC->ETH->NEO", "ETH->NEO->BTC->ETH", "ETH->BTC->NEO->ETH")
  finish_table <- find_result(finish_table, 23, table_OMG_ETH, OMG, ETH, "OMG->ETH->BTC->OMG", "OMG->BTC->ETH->OMG", "ETH->OMG->BTC->ETH", "ETH->BTC->OMG->ETH")
  finish_table <- find_result(finish_table, 24, table_ONT_USDT, ONT, BTC, "ONT->BTC->USDT->ONT", "ONT->USDT->BTC->ONT", "BTC->ONT->USDT->BTC", "BTC->USDT->ONT->BTC")
  finish_table <- find_result(finish_table, 25, table_ONT_ETH, ONT, ETH, "ONT->ETH->BTC->ONT", "ONT->BTC->ETH->ONT", "ETH->ONT->BTC->ETH", "ETH->BTC->ONT->ETH")
  finish_table <- find_result(finish_table, 26, table_QTUM_USDT, QTUM, BTC, "QTUM->BTC->USDT->QTUM", "QTUM->USDT->BTC->QTUM", "BTC->QTUM->USDT->BTC", "BTC->USDT->QTUM->BTC")
  finish_table <- find_result(finish_table, 27, table_QTUM_ETH, QTUM, ETH, "QTUM->ETH->BTC->QTUM", "QTUM->BTC->ETH->QTUM", "ETH->QTUM->BTC->ETH", "ETH->BTC->QTUM->ETH")
  finish_table <- find_result(finish_table, 28, table_SNT_ETH, SNT, ETH, "SNT->ETH->BTC->SNT", "SNT->BTC->ETH->SNT", "ETH->SNT->BTC->ETH", "ETH->BTC->SNT->ETH")
  finish_table <- find_result(finish_table, 29, table_STRAT_ETH, STRAT, ETH, "STRAT->ETH->BTC->STRAT", "STRAT->BTC->ETH->STRAT", "ETH->STRAT->BTC->ETH", "ETH->BTC->STRAT->ETH")
  finish_table <- find_result(finish_table, 30, table_TRX_USDT, TRX, BTC, "TRX->BTC->USDT->TRX", "TRX->USDT->BTC->TRX", "BTC->TRX->USDT->BTC", "BTC->USDT->TRX->BTC")
  finish_table <- find_result(finish_table, 31, table_TRX_ETH, TRX, ETH, "TRX->ETH->BTC->TRX", "TRX->BTC->ETH->TRX", "ETH->TRX->BTC->ETH", "ETH->BTC->TRX->ETH")
  finish_table <- find_result(finish_table, 32, table_VET_USDT, VET, BTC, "VET->BTC->USDT->VET", "VET->USDT->BTC->VET", "BTC->VET->USDT->BTC", "BTC->USDT->VET->BTC")
  finish_table <- find_result(finish_table, 33, table_VET_ETH, VET, ETH, "VET->ETH->BTC->VET", "VET->BTC->ETH->VET", "ETH->VET->BTC->ETH", "ETH->BTC->VET->ETH")
  finish_table <- find_result(finish_table, 34, table_WAVES_ETH, WAVES, ETH, "WAVES->ETH->BTC->WAVES", "WAVES->BTC->ETH->WAVES", "ETH->WAVES->BTC->ETH", "ETH->BTC->WAVES->ETH")
  finish_table <- find_result(finish_table, 35, table_XEM_ETH, XEM, ETH, "XEM->ETH->BTC->XEM", "XEM->BTC->ETH->XEM", "ETH->XEM->BTC->ETH", "ETH->BTC->XEM->ETH")
  finish_table <- find_result(finish_table, 36, table_XLM_USDT, XLM, BTC, "XLM->BTC->USDT->XLM", "XLM->USDT->BTC->XLM", "BTC->XLM->USDT->BTC", "BTC->USDT->XLM->BTC")
  finish_table <- find_result(finish_table, 37, table_XLM_ETH, XLM, ETH, "XLM->ETH->BTC->XLM", "XLM->BTC->ETH->XLM", "ETH->XLM->BTC->ETH", "ETH->BTC->XLM->ETH")
  finish_table <- find_result(finish_table, 38, table_XMR_ETH, XMR, ETH, "XMR->ETH->BTC->XMR", "XMR->BTC->ETH->XMR", "ETH->XMR->BTC->ETH", "ETH->BTC->XMR->ETH")
  finish_table <- find_result(finish_table, 39, table_XRP_USDT, XRP, BTC, "XRP->BTC->USDT->XRP", "XRP->USDT->BTC->XRP", "BTC->XRP->USDT->BTC", "BTC->USDT->XRP->BTC")
  finish_table <- find_result(finish_table, 40, table_XRP_ETH, XRP, ETH, "XRP->ETH->BTC->XRP", "XRP->BTC->ETH->XRP", "ETH->XRP->BTC->ETH", "ETH->BTC->XRP->ETH")
  finish_table <- find_result(finish_table, 41, table_XVG_ETH, XVG, ETH, "XVG->ETH->BTC->XVG", "XVG->BTC->ETH->XVG", "ETH->XVG->BTC->ETH", "ETH->BTC->XVG->ETH")
  finish_table <- find_result(finish_table, 42, table_ZEC_ETH, ZEC, ETH, "ZEC->ETH->BTC->ZEC", "ZEC->BTC->ETH->ZEC", "ETH->ZEC->BTC->ETH", "ETH->BTC->ZEC->ETH")
  finish_table <- find_result(finish_table, 43, table_ZRX_ETH, ZRX, ETH, "ZRX->ETH->BTC->ZRX", "ZRX->BTC->ETH->ZRX", "ETH->ZRX->BTC->ETH", "ETH->BTC->ZRX->ETH")
  
  # ------------------
  return(finish_table)
}
