source("main_func.R")

bittrex_func <- function(finish_table, lim_or_mark, data_market_price){
  # заполнение курсов binance
  get_price_bittrex <- function(Name_crypt1, Name_crypt2, Name_crypt3, table_Crypto, lim_or_mark, data_market_price){
    # преобразуем list в data.frame
    data <- as.data.frame(do.call(rbind, data_market_price[["result"]]))
    
    switch(lim_or_mark, 
           lim={
             # заполняем строчку курсов для limit price
             # при прямой --------------------------------------------------
             table_Crypto[1,2] <- as.numeric(data[data[,1]==Name_crypt1,"Bid"])
             table_Crypto[1,3] <- as.numeric(data[data[,1]==Name_crypt2,"Bid"])
             table_Crypto[1,4] <- 1/(as.numeric(data[data[,1]==Name_crypt3,"Ask"]))
             table_Crypto[1,10] <- 1/(as.numeric(data[data[,1]==Name_crypt1,"Ask"]))
             table_Crypto[1,11] <- as.numeric(data[data[,1]==Name_crypt3,"Bid"])
             table_Crypto[1,12] <- 1/(as.numeric(data[data[,1]==Name_crypt2,"Ask"]))
             # при обратной ------------------------------------------------
             table_Crypto[1,6] <- as.numeric(data[data[,1]==Name_crypt3,"Bid"])
             table_Crypto[1,7] <- 1/(as.numeric(data[data[,1]==Name_crypt2,"Ask"]))
             table_Crypto[1,8] <- 1/(as.numeric(data[data[,1]==Name_crypt1,"Ask"]))
             table_Crypto[1,14] <- as.numeric(data[data[,1]==Name_crypt2,"Bid"])
             table_Crypto[1,15] <- 1/(as.numeric(data[data[,1]==Name_crypt3,"Ask"]))
             table_Crypto[1,16] <- as.numeric(data[data[,1]==Name_crypt1,"Bid"])
           },
           mark={
             # заполняем строчку курсов для market price
             # при прямой --------------------------------------------------
             table_Crypto[1,2] <- as.numeric(data[data[,1]==Name_crypt1,"Last"])
             table_Crypto[1,3] <- as.numeric(data[data[,1]==Name_crypt2,"Last"])
             table_Crypto[1,4] <- 1/(as.numeric(data[data[,1]==Name_crypt3,"Last"]))
             table_Crypto[1,10] <- 1/(as.numeric(data[data[,1]==Name_crypt1,"Last"]))
             table_Crypto[1,11] <- as.numeric(data[data[,1]==Name_crypt3,"Last"])
             table_Crypto[1,12] <- 1/(as.numeric(data[data[,1]==Name_crypt2,"Last"]))
             # при обратной ------------------------------------------------
             table_Crypto[1,6] <- as.numeric(data[data[,1]==Name_crypt3,"Last"])
             table_Crypto[1,7] <- 1/(as.numeric(data[data[,1]==Name_crypt2,"Last"]))
             table_Crypto[1,8] <- 1/(as.numeric(data[data[,1]==Name_crypt1,"Last"]))
             table_Crypto[1,14] <- as.numeric(data[data[,1]==Name_crypt2,"Last"])
             table_Crypto[1,15] <- 1/(as.numeric(data[data[,1]==Name_crypt3,"Last"]))
             table_Crypto[1,16] <- as.numeric(data[data[,1]==Name_crypt1,"Last"])
           })
    # ------------------
    return(table_Crypto)
  }
  
  # -----------------------------------------------------------------------------------
  # узнать номер криптовалютной пары для первых 3 параметров в нижних функциях
  #what_num_crypt<-as.data.frame.raw(data_market_price[["result"]])
  #View(what_num_crypt)
  
  # заполняем значение курса
  table_ADA_USDT <- get_price_bittrex("BTC-ADA", "USDT-BTC", "USDT-ADA", table_ADA_USDT, lim_or_mark, data_market_price)
  table_ADA_ETH <- get_price_bittrex("ETH-ADA", "BTC-ETH", "BTC-ADA", table_ADA_ETH, lim_or_mark, data_market_price)
  table_BCH_USDT <- get_price_bittrex("BTC-BCH", "USDT-BTC", "USDT-BCH", table_BCH_USDT, lim_or_mark, data_market_price)
  table_BCH_ETH <- get_price_bittrex("ETH-BCH", "BTC-ETH", "BTC-BCH", table_BCH_ETH, lim_or_mark, data_market_price)
  table_DASH_USDT <- get_price_bittrex("BTC-DASH", "USDT-BTC", "USDT-DASH", table_DASH_USDT, lim_or_mark, data_market_price)
  table_DASH_ETH <- get_price_bittrex("ETH-DASH", "BTC-ETH", "BTC-DASH", table_DASH_ETH, lim_or_mark, data_market_price)
  table_DCR_USDT <- get_price_bittrex("BTC-DCR", "USDT-BTC", "USDT-DCR", table_DCR_USDT, lim_or_mark, data_market_price)
  table_DGB_USDT <- get_price_bittrex("BTC-DGB", "USDT-BTC", "USDT-DGB", table_DGB_USDT, lim_or_mark, data_market_price)
  table_DGB_ETH <- get_price_bittrex("ETH-DGB", "BTC-ETH", "BTC-DGB", table_DGB_ETH, lim_or_mark, data_market_price)
  table_ETC_USDT <- get_price_bittrex("BTC-ETC", "USDT-BTC", "USDT-ETC", table_ETC_USDT, lim_or_mark, data_market_price)
  table_ETC_ETH <- get_price_bittrex("ETH-ETC", "BTC-ETH", "BTC-ETC", table_ETC_ETH, lim_or_mark, data_market_price)
  table_ETH_USDT <- get_price_bittrex("BTC-ETH", "USDT-BTC", "USDT-ETH", table_ETH_USDT, lim_or_mark, data_market_price)
  table_GNT_ETH <- get_price_bittrex("ETH-GNT", "BTC-ETH", "BTC-GNT", table_GNT_ETH, lim_or_mark, data_market_price)
  table_LTC_USDT <- get_price_bittrex("BTC-LTC", "USDT-BTC", "USDT-LTC", table_LTC_USDT, lim_or_mark, data_market_price)
  table_LTC_ETH <- get_price_bittrex("ETH-LTC", "BTC-ETH", "BTC-LTC", table_LTC_ETH, lim_or_mark, data_market_price)
  table_NEO_USDT <- get_price_bittrex("BTC-NEO", "USDT-BTC", "USDT-NEO", table_NEO_USDT, lim_or_mark, data_market_price) 
  table_NEO_ETH <- get_price_bittrex("ETH-NEO", "BTC-ETH", "BTC-NEO", table_NEO_ETH, lim_or_mark, data_market_price)
  table_OMG_USDT <- get_price_bittrex("BTC-OMG", "USDT-BTC", "USDT-OMG", table_OMG_USDT, lim_or_mark, data_market_price)
  table_OMG_ETH <- get_price_bittrex("ETH-OMG", "BTC-ETH", "BTC-OMG", table_OMG_ETH, lim_or_mark, data_market_price)
  table_QTUM_ETH <- get_price_bittrex("ETH-QTUM", "BTC-ETH", "BTC-QTUM", table_QTUM_ETH, lim_or_mark, data_market_price)
  table_SNT_ETH <- get_price_bittrex("ETH-SNT", "BTC-ETH", "BTC-SNT", table_SNT_ETH, lim_or_mark, data_market_price)
  table_STRAT_ETH <- get_price_bittrex("ETH-STRAT", "BTC-ETH", "BTC-STRAT", table_STRAT_ETH, lim_or_mark, data_market_price)
  table_SC_USDT <- get_price_bittrex("BTC-SC", "USDT-BTC", "USDT-SC", table_SC_USDT, lim_or_mark, data_market_price)
  table_SC_ETH <- get_price_bittrex("ETH-SC", "BTC-ETH", "BTC-SC", table_SC_ETH, lim_or_mark, data_market_price)
  table_TRX_USDT <- get_price_bittrex("BTC-TRX", "USDT-BTC", "USDT-TRX", table_TRX_USDT, lim_or_mark, data_market_price)
  table_TRX_ETH <- get_price_bittrex("ETH-TRX", "BTC-ETH", "BTC-TRX", table_TRX_ETH, lim_or_mark, data_market_price)
  table_WAVES_ETH <- get_price_bittrex("ETH-WAVES", "BTC-ETH", "BTC-WAVES", table_WAVES_ETH, lim_or_mark, data_market_price) 
  table_WAX_ETH <- get_price_bittrex("ETH-WAX", "BTC-ETH", "BTC-WAX", table_WAX_ETH, lim_or_mark, data_market_price)
  table_XEM_ETH <- get_price_bittrex("ETH-XEM", "BTC-ETH", "BTC-XEM", table_XEM_ETH, lim_or_mark, data_market_price)
  table_XLM_ETH <- get_price_bittrex("ETH-XLM", "BTC-ETH", "BTC-XLM", table_XLM_ETH, lim_or_mark, data_market_price)
  table_XMR_USDT <- get_price_bittrex("BTC-XMR", "USDT-BTC", "USDT-XMR", table_XMR_USDT, lim_or_mark, data_market_price)
  table_XMR_ETH <- get_price_bittrex("ETH-XMR", "BTC-ETH", "BTC-XMR", table_XMR_ETH, lim_or_mark, data_market_price)
  table_XRP_USDT <- get_price_bittrex("BTC-XRP", "USDT-BTC", "USDT-XRP", table_XRP_USDT, lim_or_mark, data_market_price)
  table_XRP_ETH <- get_price_bittrex("ETH-XRP", "BTC-ETH", "BTC-XRP", table_XRP_ETH, lim_or_mark, data_market_price)
  table_XVG_USDT <- get_price_bittrex("BTC-XVG", "USDT-BTC", "USDT-XVG", table_XVG_USDT, lim_or_mark, data_market_price)
  table_ZEC_USDT <- get_price_bittrex("BTC-ZEC", "USDT-BTC", "USDT-ZEC", table_ZEC_USDT, lim_or_mark, data_market_price)
  table_ZEC_ETH <- get_price_bittrex("ETH-ZEC", "BTC-ETH", "BTC-ZEC", table_ZEC_ETH, lim_or_mark, data_market_price)
  table_ZRX_ETH <- get_price_bittrex("ETH-ZRX", "BTC-ETH", "BTC-ZRX", table_ZRX_ETH, lim_or_mark, data_market_price)
  
  # -----------------------------------------------------------------------------------
  # выполняем расчет и заполняем строчки
  # https://bittrex.com/api/v1.1/public/getmarkets - тут смотрим делители, а именно колличество знаков после запятой (del1.1 - MinTradeSize первой пары, del2.1 - MinTradeSize второй пары, del3.1 - MinTradeSize третьей пары) ... https://bittrex.com/api/v1.1/public/getmarketsummaries - тут смотрим (del1.2 - High первой пары, del2.2 - High второй пары, del3.2 - High третьей пары)
  table_ADA_USDT <- find_balance(table_ADA_USDT, ADA, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_ADA_ETH <- find_balance(table_ADA_ETH, ADA, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_BCH_USDT <- find_balance(table_BCH_USDT, BCH, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_BCH_ETH <- find_balance(table_BCH_ETH, BCH, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_DASH_USDT <- find_balance(table_DASH_USDT, DASH, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_DASH_ETH <- find_balance(table_DASH_ETH, DASH, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_DCR_USDT <- find_balance(table_DCR_USDT, DCR, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_DGB_USDT <- find_balance(table_DGB_USDT, DGB, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_DGB_ETH <- find_balance(table_DGB_ETH, DGB, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_ETC_USDT <- find_balance(table_ETC_USDT, ETC, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_ETC_ETH <- find_balance(table_ETC_ETH, ETC, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_ETH_USDT <- find_balance(table_ETH_USDT, ETH, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_GNT_ETH <- find_balance(table_GNT_ETH, GNT, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_LTC_USDT <- find_balance(table_LTC_USDT, LTC, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_LTC_ETH <- find_balance(table_LTC_ETH, LTC, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_NEO_USDT <- find_balance(table_NEO_USDT, NEO, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_NEO_ETH <- find_balance(table_NEO_ETH, NEO, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_OMG_USDT <- find_balance(table_OMG_USDT, OMG, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_OMG_ETH <- find_balance(table_OMG_ETH, OMG, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_QTUM_ETH <- find_balance(table_QTUM_ETH, QTUM, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_SNT_ETH <- find_balance(table_SNT_ETH, SNT, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_STRAT_ETH <- find_balance(table_STRAT_ETH, STRAT, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_SC_USDT <- find_balance(table_SC_USDT, SC, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_SC_ETH <- find_balance(table_SC_ETH, SC, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_TRX_USDT <- find_balance(table_TRX_USDT, TRX, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_TRX_ETH <- find_balance(table_TRX_ETH, TRX, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_WAVES_ETH <- find_balance(table_WAVES_ETH, WAVES, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_WAX_ETH <- find_balance(table_WAX_ETH, WAX, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_XEM_ETH <- find_balance(table_XEM_ETH, XEM, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_XLM_ETH <- find_balance(table_XLM_ETH, XLM, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_XMR_USDT <- find_balance(table_XMR_USDT, XMR, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_XMR_ETH <- find_balance(table_XMR_ETH, XMR, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_XRP_USDT <- find_balance(table_XRP_USDT, XRP, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_XRP_ETH <- find_balance(table_XRP_ETH, XRP, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_XVG_USDT <- find_balance(table_XVG_USDT, XVG, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_ZEC_USDT <- find_balance(table_ZEC_USDT, ZEC, BTC, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_ZEC_ETH <- find_balance(table_ZEC_ETH, ZEC, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  table_ZRX_ETH <- find_balance(table_ZRX_ETH, ZRX, ETH, bittrex_fee, 8, 8, 8, 8, 8, 8)
  
  # -----------------------------------------------------------------------------------
  # готовим отчет
  finish_table <- find_result(finish_table, 1, table_ADA_USDT, ADA, BTC, "ADA->BTC->USDT->ADA", "ADA->USDT->BTC->ADA", "BTC->ADA->USDT->BTC", "BTC->USDT->ADA->BTC")
  finish_table <- find_result(finish_table, 2, table_ADA_ETH, ADA, ETH, "ADA->ETH->BTC->ADA", "ADA->BTC->ETH->ADA", "ETH->ADA->BTC->ETH", "ETH->BTC->ADA->ETH")
  finish_table <- find_result(finish_table, 3, table_BCH_USDT, BCH, BTC, "BCH->BTC->USDT->BCH", "BCH->USDT->BTC->BCH", "BTC->BCH->USDT->BTC", "BTC->USDT->BCH->BTC")
  finish_table <- find_result(finish_table, 4, table_BCH_ETH, BCH, ETH, "BCH->ETH->BTC->BCH", "BCH->BTC->ETH->BCH", "ETH->BCH->BTC->ETH", "ETH->BTC->BCH->ETH")
  finish_table <- find_result(finish_table, 7, table_DASH_USDT, DASH, BTC, "DASH->BTC->USDT->DASH", "DASH->USDT->BTC->DASH", "BTC->DASH->USDT->BTC", "BTC->USDT->DASH->BTC")
  finish_table <- find_result(finish_table, 8, table_DASH_ETH, DASH, ETH, "DASH->ETH->BTC->DASH", "DASH->BTC->ETH->DASH", "ETH->DASH->BTC->ETH", "ETH->BTC->DASH->ETH")
  finish_table <- find_result(finish_table, 9, table_DCR_USDT, DCR, BTC, "DCR->BTC->USDT->DCR", "DCR->USDT->BTC->DCR", "BTC->DCR->USDT->BTC", "BTC->USDT->DCR->BTC")
  finish_table <- find_result(finish_table, 10, table_DGB_USDT, DGB, BTC, "DGB->BTC->USDT->DGB", "DGB->USDT->BTC->DGB", "BTC->DGB->USDT->BTC", "BTC->USDT->DGB->BTC")
  finish_table <- find_result(finish_table, 11, table_DGB_ETH, DGB, ETH, "DGB->ETH->BTC->DGB", "DGB->BTC->ETH->DGB", "ETH->DGB->BTC->ETH", "ETH->BTC->DGB->ETH")
  finish_table <- find_result(finish_table, 12, table_ETC_USDT, ETC, BTC, "ETC->BTC->USDT->ETC", "ETC->USDT->BTC->ETC", "BTC->ETC->USDT->BTC", "BTC->USDT->ETC->BTC")
  finish_table <- find_result(finish_table, 13, table_ETC_ETH, ETC, ETH, "ETC->ETH->BTC->ETC", "ETC->BTC->ETH->ETC", "ETH->ETC->BTC->ETH", "ETH->BTC->ETC->ETH")
  finish_table <- find_result(finish_table, 14, table_ETH_USDT, ETH, BTC, "ETH->BTC->USDT->ETH", "ETH->USDT->BTC->ETH", "BTC->ETH->USDT->BTC", "BTC->USDT->ETH->BTC")
  finish_table <- find_result(finish_table, 15, table_GNT_ETH, GNT, ETH, "GNT->ETH->BTC->GNT", "GNT->BTC->ETH->GNT", "ETH->GNT->BTC->ETH", "ETH->BTC->GNT->ETH")
  finish_table <- find_result(finish_table, 16, table_LTC_USDT, LTC, BTC, "LTC->BTC->USDT->LTC", "LTC->USDT->BTC->LTC", "BTC->LTC->USDT->BTC", "BTC->USDT->LTC->BTC")
  finish_table <- find_result(finish_table, 17, table_LTC_ETH, LTC, ETH, "LTC->ETH->BTC->LTC", "LTC->BTC->ETH->LTC", "ETH->LTC->BTC->ETH", "ETH->BTC->LTC->ETH")
  finish_table <- find_result(finish_table, 18, table_NEO_USDT, NEO, BTC, "NEO->BTC->USDT->NEO", "NEO->USDT->BTC->NEO", "BTC->NEO->USDT->BTC", "BTC->USDT->NEO->BTC")
  finish_table <- find_result(finish_table, 19, table_NEO_ETH, NEO, ETH, "NEO->ETH->BTC->NEO", "NEO->BTC->ETH->NEO", "ETH->NEO->BTC->ETH", "ETH->BTC->NEO->ETH")
  finish_table <- find_result(finish_table, 20, table_OMG_USDT, OMG, BTC, "OMG->BTC->USDT->OMG", "OMG->USDT->BTC->OMG", "BTC->OMG->USDT->BTC", "BTC->USDT->OMG->BTC")
  finish_table <- find_result(finish_table, 21, table_OMG_ETH, OMG, ETH, "OMG->ETH->BTC->OMG", "OMG->BTC->ETH->OMG", "ETH->OMG->BTC->ETH", "ETH->BTC->OMG->ETH")
  finish_table <- find_result(finish_table, 22, table_QTUM_ETH, QTUM, ETH, "QTUM->ETH->BTC->QTUM", "QTUM->BTC->ETH->QTUM", "ETH->QTUM->BTC->ETH", "ETH->BTC->QTUM->ETH")
  finish_table <- find_result(finish_table, 24, table_SNT_ETH, SNT, ETH, "SNT->ETH->BTC->SNT", "SNT->BTC->ETH->SNT", "ETH->SNT->BTC->ETH", "ETH->BTC->SNT->ETH")
  finish_table <- find_result(finish_table, 25, table_STRAT_ETH, STRAT, ETH, "STRAT->ETH->BTC->STRAT", "STRAT->BTC->ETH->STRAT", "ETH->STRAT->BTC->ETH", "ETH->BTC->STRAT->ETH")
  finish_table <- find_result(finish_table, 26, table_SC_USDT, SC, BTC, "SC->BTC->USDT->SC", "SC->USDT->BTC->SC", "BTC->SC->USDT->BTC", "BTC->USDT->SC->BTC")
  finish_table <- find_result(finish_table, 27, table_SC_ETH, SC, ETH, "SC->ETH->BTC->SC", "SC->BTC->ETH->SC", "ETH->SC->BTC->ETH", "ETH->BTC->SC->ETH")
  finish_table <- find_result(finish_table, 28, table_TRX_USDT, TRX, BTC, "TRX->BTC->USDT->TRX", "TRX->USDT->BTC->TRX", "BTC->TRX->USDT->BTC", "BTC->USDT->TRX->BTC")
  finish_table <- find_result(finish_table, 29, table_TRX_ETH, TRX, ETH, "TRX->ETH->BTC->TRX", "TRX->BTC->ETH->TRX", "ETH->TRX->BTC->ETH", "ETH->BTC->TRX->ETH")
  finish_table <- find_result(finish_table, 30, table_WAVES_ETH, WAVES, ETH, "WAVES->ETH->BTC->WAVES", "WAVES->BTC->ETH->WAVES", "ETH->WAVES->BTC->ETH", "ETH->BTC->WAVES->ETH")
  finish_table <- find_result(finish_table, 31, table_WAX_ETH, WAX, ETH, "WAX->ETH->BTC->WAX", "WAX->BTC->ETH->WAX", "ETH->WAX->BTC->ETH", "ETH->BTC->WAX->ETH")
  finish_table <- find_result(finish_table, 32, table_XEM_ETH, XEM, ETH, "XEM->ETH->BTC->XEM", "XEM->BTC->ETH->XEM", "ETH->XEM->BTC->ETH", "ETH->BTC->XEM->ETH")
  finish_table <- find_result(finish_table, 33, table_XLM_ETH, XLM, ETH, "XLM->ETH->BTC->XLM", "XLM->BTC->ETH->XLM", "ETH->XLM->BTC->ETH", "ETH->BTC->XLM->ETH")
  finish_table <- find_result(finish_table, 34, table_XMR_USDT, XMR, BTC, "XMR->BTC->USDT->XMR", "XMR->USDT->BTC->XMR", "BTC->XMR->USDT->BTC", "BTC->USDT->XMR->BTC")
  finish_table <- find_result(finish_table, 35, table_XMR_ETH, XMR, ETH, "XMR->ETH->BTC->XMR", "XMR->BTC->ETH->XMR", "ETH->XMR->BTC->ETH", "ETH->BTC->XMR->ETH")
  finish_table <- find_result(finish_table, 36, table_XRP_USDT, XRP, BTC, "XRP->BTC->USDT->XRP", "XRP->USDT->BTC->XRP", "BTC->XRP->USDT->BTC", "BTC->USDT->XRP->BTC")
  finish_table <- find_result(finish_table, 37, table_XRP_ETH, XRP, ETH, "XRP->ETH->BTC->XRP", "XRP->BTC->ETH->XRP", "ETH->XRP->BTC->ETH", "ETH->BTC->XRP->ETH")
  finish_table <- find_result(finish_table, 38, table_XVG_USDT, XVG, BTC, "XVG->BTC->USDT->XVG", "XVG->USDT->BTC->XVG", "BTC->XVG->USDT->BTC", "BTC->USDT->XVG->BTC")
  finish_table <- find_result(finish_table, 23, table_ZEC_USDT, ZEC, BTC, "ZEC->BTC->USDT->ZEC", "ZEC->USDT->BTC->ZEC", "BTC->ZEC->USDT->BTC", "BTC->USDT->ZEC->BTC")
  finish_table <- find_result(finish_table, 5, table_ZEC_ETH, ZEC, ETH, "ZEC->ETH->BTC->ZEC", "ZEC->BTC->ETH->ZEC", "ETH->ZEC->BTC->ETH", "ETH->BTC->ZEC->ETH")
  finish_table <- find_result(finish_table, 6, table_ZRX_ETH, ZRX, ETH, "ZRX->ETH->BTC->ZRX", "ZRX->BTC->ETH->ZRX", "ETH->ZRX->BTC->ETH", "ETH->BTC->ZRX->ETH")
  
  # ------------------
  return(finish_table)
}
