source("main_func.R")

hitbtc_func <- function(finish_table, lim_or_mark, data_market_price){
  # заполнение курсов binance
  get_price_hitbtc <- function(Name_crypt1, Name_crypt2, Name_crypt3, table_Crypto, lim_or_mark, data_market_price){
    # преобразуем list в data.frame
    data <- as.data.frame(do.call(rbind, data_market_price))
    
    switch(lim_or_mark, 
           lim={
             # заполняем строчку курсов для limit price
             # при прямой --------------------------------------------------
             table_Crypto[1,2] <- as.numeric(data[data[,10]==Name_crypt1,"bid"])
             table_Crypto[1,3] <- as.numeric(data[data[,10]==Name_crypt2,"bid"])
             table_Crypto[1,4] <- 1/(as.numeric(data[data[,10]==Name_crypt3,"ask"]))
             table_Crypto[1,10] <- 1/(as.numeric(data[data[,10]==Name_crypt1,"ask"]))
             table_Crypto[1,11] <- as.numeric(data[data[,10]==Name_crypt3,"bid"])
             table_Crypto[1,12] <- 1/(as.numeric(data[data[,10]==Name_crypt2,"ask"]))
             # при обратной ------------------------------------------------
             table_Crypto[1,6] <- as.numeric(data[data[,10]==Name_crypt3,"bid"])
             table_Crypto[1,7] <- 1/(as.numeric(data[data[,10]==Name_crypt2,"ask"]))
             table_Crypto[1,8] <- 1/(as.numeric(data[data[,10]==Name_crypt1,"ask"]))
             table_Crypto[1,14] <- as.numeric(data[data[,10]==Name_crypt2,"bid"])
             table_Crypto[1,15] <- 1/(as.numeric(data[data[,10]==Name_crypt3,"ask"]))
             table_Crypto[1,16] <- as.numeric(data[data[,10]==Name_crypt1,"bid"])
           },
           mark={
             # заполняем строчку курсов для market price
             # при прямой --------------------------------------------------
             table_Crypto[1,2] <- as.numeric(data[data[,10]==Name_crypt1,"last"])
             table_Crypto[1,3] <- as.numeric(data[data[,10]==Name_crypt2,"last"])
             table_Crypto[1,4] <- 1/(as.numeric(data[data[,10]==Name_crypt3,"last"]))
             table_Crypto[1,10] <- 1/(as.numeric(data[data[,10]==Name_crypt1,"last"]))
             table_Crypto[1,11] <- as.numeric(data[data[,10]==Name_crypt3,"last"])
             table_Crypto[1,12] <- 1/(as.numeric(data[data[,10]==Name_crypt2,"last"]))
             # при обратной ------------------------------------------------
             table_Crypto[1,6] <- as.numeric(data[data[,10]==Name_crypt3,"last"])
             table_Crypto[1,7] <- 1/(as.numeric(data[data[,10]==Name_crypt2,"last"]))
             table_Crypto[1,8] <- 1/(as.numeric(data[data[,10]==Name_crypt1,"last"]))
             table_Crypto[1,14] <- as.numeric(data[data[,10]==Name_crypt2,"last"])
             table_Crypto[1,15] <- 1/(as.numeric(data[data[,10]==Name_crypt3,"last"]))
             table_Crypto[1,16] <- as.numeric(data[data[,10]==Name_crypt1,"last"])
           })
    # ------------------
    return(table_Crypto)
  }
  
  # -----------------------------------------------------------------------------------
  # узнать номер криптовалютной пары для первых 3 параметров в нижних функциях
  #what_num_crypt<-as.data.frame.raw(data_market_price)
  #View(what_num_crypt)
  
  # заполняем значение курса
  table_ADA_USDT <- get_price_hitbtc("ADABTC", "BTCUSD", "ADAUSD", table_ADA_USDT, lim_or_mark, data_market_price)
  table_ADA_ETH <- get_price_hitbtc("ADAETH", "ETHBTC", "ADABTC", table_ADA_ETH, lim_or_mark, data_market_price)
  table_BCH_USDT <- get_price_hitbtc("BCHBTC", "BTCUSD", "BCHUSD", table_BCH_USDT, lim_or_mark, data_market_price) 
  table_BCH_ETH <- get_price_hitbtc("BCHETH", "ETHBTC", "BCHBTC", table_BCH_ETH, lim_or_mark, data_market_price)
  table_BCN_USDT <- get_price_hitbtc("BCNBTC", "BTCUSD", "BCNUSD", table_BCN_USDT, lim_or_mark, data_market_price)
  table_BCN_ETH <- get_price_hitbtc("BCNETH", "ETHBTC", "BCNBTC", table_BCN_ETH, lim_or_mark, data_market_price)
  table_DASH_USDT <- get_price_hitbtc("DASHBTC", "BTCUSD", "DASHUSD", table_DASH_USDT, lim_or_mark, data_market_price)
  table_DASH_ETH <- get_price_hitbtc("DASHETH", "ETHBTC", "DASHBTC", table_DASH_ETH, lim_or_mark, data_market_price)
  table_DOGE_USDT <- get_price_hitbtc("DOGEBTC", "BTCUSD", "DOGEUSD", table_DOGE_USDT, lim_or_mark, data_market_price)
  table_DOGE_ETH <- get_price_hitbtc("DOGEETH", "ETHBTC", "DOGEBTC", table_DOGE_ETH, lim_or_mark, data_market_price)
  table_EOS_USDT <- get_price_hitbtc("EOSBTC", "BTCUSD", "EOSUSD", table_EOS_USDT, lim_or_mark, data_market_price) 
  table_EOS_ETH <- get_price_hitbtc("EOSETH", "ETHBTC", "EOSBTC", table_EOS_ETH, lim_or_mark, data_market_price)
  table_ETC_USDT <- get_price_hitbtc("ETCBTC", "BTCUSD", "ETCUSD", table_ETC_USDT, lim_or_mark, data_market_price)
  table_ETC_ETH <- get_price_hitbtc("ETCETH", "ETHBTC", "ETCBTC", table_ETC_ETH, lim_or_mark, data_market_price)
  table_ETH_USDT <- get_price_hitbtc("ETHBTC", "BTCUSD", "ETHUSD", table_ETH_USDT, lim_or_mark, data_market_price)
  table_LSK_USDT <- get_price_hitbtc("LSKBTC", "BTCUSD", "LSKUSD", table_LSK_USDT, lim_or_mark, data_market_price)
  table_LSK_ETH <- get_price_hitbtc("LSKETH", "ETHBTC", "LSKBTC", table_LSK_ETH, lim_or_mark, data_market_price) 
  table_LTC_USDT <- get_price_hitbtc("LTCBTC", "BTCUSD", "LTCUSD", table_LTC_USDT, lim_or_mark, data_market_price) 
  table_LTC_ETH <- get_price_hitbtc("LTCETH", "ETHBTC", "LTCBTC", table_LTC_ETH, lim_or_mark, data_market_price) 
  table_NEO_USDT <- get_price_hitbtc("NEOBTC", "BTCUSD", "NEOUSD", table_NEO_USDT, lim_or_mark, data_market_price)
  table_NEO_ETH <- get_price_hitbtc("NEOETH", "ETHBTC", "NEOBTC", table_NEO_ETH, lim_or_mark, data_market_price)
  table_OMG_USDT <- get_price_hitbtc("OMGBTC", "BTCUSD", "OMGUSD", table_OMG_USDT, lim_or_mark, data_market_price)
  table_OMG_ETH <- get_price_hitbtc("OMGETH", "ETHBTC", "OMGBTC", table_OMG_ETH, lim_or_mark, data_market_price)
  table_TRX_USDT <- get_price_hitbtc("TRXBTC", "BTCUSD", "TRXUSD", table_TRX_USDT, lim_or_mark, data_market_price)
  table_TRX_ETH <- get_price_hitbtc("TRXETH", "ETHBTC", "TRXBTC", table_TRX_ETH, lim_or_mark, data_market_price)
  table_XEM_USDT <- get_price_hitbtc("XEMBTC", "BTCUSD", "XEMUSD", table_XEM_USDT, lim_or_mark, data_market_price)
  table_XEM_ETH <- get_price_hitbtc("XEMETH", "ETHBTC", "XEMBTC", table_XEM_ETH, lim_or_mark, data_market_price)
  table_XLM_USDT <- get_price_hitbtc("XLMBTC", "BTCUSD", "XLMUSD", table_XLM_USDT, lim_or_mark, data_market_price)
  table_XLM_ETH <- get_price_hitbtc("XLMETH", "ETHBTC", "XLMBTC", table_XLM_ETH, lim_or_mark, data_market_price)
  table_XMR_USDT <- get_price_hitbtc("XMRBTC", "BTCUSD", "XMRUSD", table_XMR_USDT, lim_or_mark, data_market_price)
  table_XMR_ETH <- get_price_hitbtc("XMRETH", "ETHBTC", "XMRBTC", table_XMR_ETH, lim_or_mark, data_market_price)
  table_XRP_ETH <- get_price_hitbtc("XRPETH", "ETHBTC", "XRPBTC", table_XRP_ETH, lim_or_mark, data_market_price)
  table_ZEC_USDT <- get_price_hitbtc("ZECBTC", "BTCUSD", "ZECUSD", table_ZEC_USDT, lim_or_mark, data_market_price)
  table_ZEC_ETH <- get_price_hitbtc("ZECETH", "ETHBTC", "ZECBTC", table_ZEC_ETH, lim_or_mark, data_market_price)
  table_ZRX_USDT <- get_price_hitbtc("ZRXBTC", "BTCUSD", "ZRXUSD", table_ZRX_USDT, lim_or_mark, data_market_price)
  table_ZRX_ETH <- get_price_hitbtc("ZRXETH", "ETHBTC", "ZRXBTC", table_ZRX_ETH, lim_or_mark, data_market_price)
  
  # -----------------------------------------------------------------------------------
  # выполняем расчет и заполняем строчки
  # https://api.hitbtc.com/api/1/public/symbols - тут смотрим делители, а именно колличество знаков после запятой (del1.1 - step первой пары, del2.1 - step второй пары, del3.1 - step третьей пары) ... (del1.2 = 8, del2.2 = 8, del3.2 = 8)
  table_ADA_USDT <- find_balance(table_ADA_USDT, ADA, BTC, hitbtc_fee, 8, 8, 2, 8, 6, 8)
  table_ADA_ETH <- find_balance(table_ADA_ETH, ADA, ETH, hitbtc_fee, 7, 8, 6, 8, 8, 8)
  table_BCH_USDT <- find_balance(table_BCH_USDT, BCH, BTC, hitbtc_fee, 6, 8, 2, 8, 5, 8)
  table_BCH_ETH <- find_balance(table_BCH_ETH, BCH, ETH, hitbtc_fee, 6, 8, 6, 8, 6, 8)
  table_BCN_USDT <- find_balance(table_BCN_USDT, BCN, BTC, hitbtc_fee, 8, 8, 2, 8, 6, 8)
  table_BCN_ETH <- find_balance(table_BCN_ETH, BCN, ETH, hitbtc_fee, 7, 8, 6, 8, 8, 8)
  table_DASH_USDT <- find_balance(table_DASH_USDT, DASH, BTC, hitbtc_fee, 6, 8, 2, 8, 2, 8)
  table_DASH_ETH <- find_balance(table_DASH_ETH, DASH, ETH, hitbtc_fee, 6, 8, 6, 8, 6, 8)
  table_DOGE_USDT <- find_balance(table_DOGE_USDT, DOGE, BTC, hitbtc_fee, 8, 8, 2, 8, 6, 8)
  table_DOGE_ETH <- find_balance(table_DOGE_ETH, DOGE, ETH, hitbtc_fee, 7, 8, 6, 8, 8, 8)
  table_EOS_USDT <- find_balance(table_EOS_USDT, EOS, BTC, hitbtc_fee, 6, 8, 2, 8, 5, 8)
  table_EOS_ETH <- find_balance(table_EOS_ETH, EOS, ETH, hitbtc_fee, 6, 8, 6, 8, 6, 8)
  table_ETC_USDT <- find_balance(table_ETC_USDT, ETC, BTC, hitbtc_fee, 6, 8, 2, 8, 2, 8)
  table_ETC_ETH <- find_balance(table_ETC_ETH, ETC, ETH, hitbtc_fee, 6, 8, 6, 8, 6, 8)
  table_ETH_USDT <- find_balance(table_ETH_USDT, ETH, BTC, hitbtc_fee, 6, 8, 2, 8, 2, 8)
  table_LSK_USDT <- find_balance(table_LSK_USDT, LSK, BTC, hitbtc_fee, 7, 8, 2, 8, 4, 8)
  table_LSK_ETH <- find_balance(table_LSK_ETH, LSK, ETH, hitbtc_fee, 5, 8, 6, 8, 7, 8)
  table_LTC_USDT <- find_balance(table_LTC_USDT, LTC, BTC, hitbtc_fee, 5, 8, 2, 8, 3, 8)
  table_LTC_ETH <- find_balance(table_LTC_ETH, LTC, ETH, hitbtc_fee, 3, 8, 6, 8, 5, 8)
  table_NEO_USDT <- find_balance(table_NEO_USDT, NEO, BTC, hitbtc_fee, 5, 8, 2, 8, 2, 8)
  table_NEO_ETH <- find_balance(table_NEO_ETH, NEO, ETH, hitbtc_fee, 4, 8, 6, 8, 5, 8)
  table_OMG_USDT <- find_balance(table_OMG_USDT, OMG, BTC, hitbtc_fee, 8, 8, 2, 8, 6, 8)
  table_OMG_ETH <- find_balance(table_OMG_ETH, OMG, ETH, hitbtc_fee, 7, 8, 6, 8, 8, 8)
  table_TRX_USDT <- find_balance(table_TRX_USDT, TRX, BTC, hitbtc_fee, 8, 8, 2, 8, 5, 8)
  table_TRX_ETH <- find_balance(table_TRX_ETH, TRX, ETH, hitbtc_fee, 7, 8, 6, 8, 8, 8)
  table_XEM_USDT <- find_balance(table_XEM_USDT, XEM, BTC, hitbtc_fee, 8, 8, 2, 8, 6, 8)
  table_XEM_ETH <- find_balance(table_XEM_ETH, XEM, ETH, hitbtc_fee, 6, 8, 6, 8, 8, 8)
  table_XLM_USDT <- find_balance(table_XLM_USDT, XLM, BTC, hitbtc_fee, 8, 8, 2, 8, 6, 8)
  table_XLM_ETH <- find_balance(table_XLM_ETH, XLM, ETH, hitbtc_fee, 7, 8, 6, 8, 8, 8)
  table_XMR_USDT <- find_balance(table_XMR_USDT, XMR, BTC, hitbtc_fee, 6, 8, 2, 8, 2, 8)
  table_XMR_ETH <- find_balance(table_XMR_ETH, XMR, ETH, hitbtc_fee, 6, 8, 6, 8, 6, 8)
  table_XRP_ETH <- find_balance(table_XRP_ETH, XRP, ETH, hitbtc_fee, 5, 8, 6, 8, 8, 8)
  table_ZEC_USDT <- find_balance(table_ZEC_USDT, ZEC, BTC, hitbtc_fee, 6, 8, 2, 8, 2, 8)
  table_ZEC_ETH <- find_balance(table_ZEC_ETH, ZEC, ETH, hitbtc_fee, 6, 8, 6, 8, 6, 8)
  table_ZRX_USDT <- find_balance(table_ZRX_USDT, ZRX, BTC, hitbtc_fee, 6, 8, 2, 8, 5, 8)
  table_ZRX_ETH <- find_balance(table_ZRX_ETH, ZRX, ETH, hitbtc_fee, 6, 8, 6, 8, 5, 8)
  
  # -----------------------------------------------------------------------------------
  # готовим отчет
  finish_table <- find_result(finish_table, 1, table_ADA_USDT, ADA, BTC, "ADA->BTC->USD->ADA", "ADA->USD->BTC->ADA", "BTC->ADA->USD->BTC", "BTC->USD->ADA->BTC")
  finish_table <- find_result(finish_table, 2, table_ADA_ETH, ADA, ETH, "ADA->ETH->BTC->ADA", "ADA->BTC->ETH->ADA", "ETH->ADA->BTC->ETH", "ETH->BTC->ADA->ETH")
  finish_table <- find_result(finish_table, 3, table_BCH_USDT, BCH, BTC, "BCH->BTC->USD->BCH", "BCH->USD->BTC->BCH", "BTC->BCH->USD->BTC", "BTC->USD->BCH->BTC")
  finish_table <- find_result(finish_table, 4, table_BCH_ETH, BCH, ETH, "BCH->ETH->BTC->BCH", "BCH->BTC->ETH->BCH", "ETH->BCH->BTC->ETH", "ETH->BTC->BCH->ETH")
  finish_table <- find_result(finish_table, 5, table_BCN_USDT, BCN, BTC, "BCN->BTC->USD->BCN", "BCN->USD->BTC->BCN", "BTC->BCN->USD->BTC", "BTC->USD->BCN->BTC")
  finish_table <- find_result(finish_table, 6, table_BCN_ETH, BCN, ETH, "BCN->ETH->BTC->BCN", "BCN->BTC->ETH->BCN", "ETH->BCN->BTC->ETH", "ETH->BTC->BCN->ETH")
  finish_table <- find_result(finish_table, 7, table_DASH_USDT, DASH, BTC, "DASH->BTC->USD->DASH", "DASH->USD->BTC->DASH", "BTC->DASH->USD->BTC", "BTC->USD->DASH->BTC")
  finish_table <- find_result(finish_table, 8, table_DASH_ETH, DASH, ETH, "DASH->ETH->BTC->DASH", "DASH->BTC->ETH->DASH", "ETH->DASH->BTC->ETH", "ETH->BTC->DASH->ETH")
  finish_table <- find_result(finish_table, 9, table_DOGE_USDT, DOGE, BTC, "DOGE->BTC->USD->DOGE", "DOGE->USD->BTC->DOGE", "BTC->DOGE->USD->BTC", "BTC->USD->DOGE->BTC")
  finish_table <- find_result(finish_table, 10, table_DOGE_ETH, DOGE, ETH, "DOGE->ETH->BTC->DOGE", "DOGE->BTC->ETH->DOGE", "ETH->DOGE->BTC->ETH", "ETH->BTC->DOGE->ETH")
  finish_table <- find_result(finish_table, 11, table_EOS_USDT, EOS, BTC, "EOS->BTC->USD->EOS", "EOS->USD->BTC->EOS", "BTC->EOS->USD->BTC", "BTC->USD->EOS->BTC")
  finish_table <- find_result(finish_table, 12, table_EOS_ETH, EOS, ETH, "EOS->ETH->BTC->EOS", "EOS->BTC->ETH->EOS", "ETH->EOS->BTC->ETH", "ETH->BTC->EOS->ETH")
  finish_table <- find_result(finish_table, 13, table_ETC_USDT, ETC, BTC, "ETC->BTC->USD->ETC", "ETC->USD->BTC->ETC", "BTC->ETC->USD->BTC", "BTC->USD->ETC->BTC")
  finish_table <- find_result(finish_table, 14, table_ETC_ETH, ETC, ETH, "ETC->ETH->BTC->ETC", "ETC->BTC->ETH->ETC", "ETH->ETC->BTC->ETH", "ETH->BTC->ETC->ETH")
  finish_table <- find_result(finish_table, 15, table_ETH_USDT, ETH, BTC, "ETH->BTC->USD->ETH", "ETH->USD->BTC->ETH", "BTC->ETH->USD->BTC", "BTC->USD->ETH->BTC")
  finish_table <- find_result(finish_table, 16, table_LSK_USDT, LSK, BTC, "LSK->BTC->USD->LSK", "LSK->USD->BTC->LSK", "BTC->LSK->USD->BTC", "BTC->USD->LSK->BTC")
  finish_table <- find_result(finish_table, 17, table_LSK_ETH, LSK, ETH, "LSK->ETH->BTC->LSK", "LSK->BTC->ETH->LSK", "ETH->LSK->BTC->ETH", "ETH->BTC->LSK->ETH")
  finish_table <- find_result(finish_table, 18, table_LTC_USDT, LTC, BTC, "LTC->BTC->USD->LTC", "LTC->USD->BTC->LTC", "BTC->LTC->USD->BTC", "BTC->USD->LTC->BTC")
  finish_table <- find_result(finish_table, 19, table_LTC_ETH, LTC, ETH, "LTC->ETH->BTC->LTC", "LTC->BTC->ETH->LTC", "ETH->LTC->BTC->ETH", "ETH->BTC->LTC->ETH")
  finish_table <- find_result(finish_table, 20, table_NEO_USDT, NEO, BTC, "NEO->BTC->USD->NEO", "NEO->USD->BTC->NEO", "BTC->NEO->USD->BTC", "BTC->USD->NEO->BTC")
  finish_table <- find_result(finish_table, 21, table_NEO_ETH, NEO, ETH, "NEO->ETH->BTC->NEO", "NEO->BTC->ETH->NEO", "ETH->NEO->BTC->ETH", "ETH->BTC->NEO->ETH")
  finish_table <- find_result(finish_table, 24, table_OMG_USDT, OMG, BTC, "OMG->BTC->USD->OMG", "OMG->USD->BTC->OMG", "BTC->OMG->USD->BTC", "BTC->USD->OMG->BTC")
  finish_table <- find_result(finish_table, 25, table_OMG_ETH, OMG, ETH, "OMG->ETH->BTC->OMG", "OMG->BTC->ETH->OMG", "ETH->OMG->BTC->ETH", "ETH->BTC->OMG->ETH")
  finish_table <- find_result(finish_table, 26, table_TRX_USDT, TRX, BTC, "TRX->BTC->USD->TRX", "TRX->USD->BTC->TRX", "BTC->TRX->USD->BTC", "BTC->USD->TRX->BTC")
  finish_table <- find_result(finish_table, 27, table_TRX_ETH, TRX, ETH, "TRX->ETH->BTC->TRX", "TRX->BTC->ETH->TRX", "ETH->TRX->BTC->ETH", "ETH->BTC->TRX->ETH")
  finish_table <- find_result(finish_table, 28, table_XEM_USDT, XEM, BTC, "XEM->BTC->USD->XEM", "XEM->USD->BTC->XEM", "BTC->XEM->USD->BTC", "BTC->USD->XEM->BTC")
  finish_table <- find_result(finish_table, 29, table_XEM_ETH, XEM, ETH, "XEM->ETH->BTC->XEM", "XEM->BTC->ETH->XEM", "ETH->XEM->BTC->ETH", "ETH->BTC->XEM->ETH")
  finish_table <- find_result(finish_table, 30, table_XLM_USDT, XLM, BTC, "XLM->BTC->USD->XLM", "XLM->USD->BTC->XLM", "BTC->XLM->USD->BTC", "BTC->USD->XLM->BTC")
  finish_table <- find_result(finish_table, 31, table_XLM_ETH, XLM, ETH, "XLM->ETH->BTC->XLM", "XLM->BTC->ETH->XLM", "ETH->XLM->BTC->ETH", "ETH->BTC->XLM->ETH")
  finish_table <- find_result(finish_table, 32, table_XMR_USDT, XMR, BTC, "XMR->BTC->USD->XMR", "XMR->USD->BTC->XMR", "BTC->XMR->USD->BTC", "BTC->USD->XMR->BTC")
  finish_table <- find_result(finish_table, 33, table_XMR_ETH, XMR, ETH, "XMR->ETH->BTC->XMR", "XMR->BTC->ETH->XMR", "ETH->XMR->BTC->ETH", "ETH->BTC->XMR->ETH")
  finish_table <- find_result(finish_table, 34, table_XRP_ETH, XRP, ETH, "XRP->ETH->BTC->XRP", "XRP->BTC->ETH->XRP", "ETH->XRP->BTC->ETH", "ETH->BTC->XRP->ETH")
  finish_table <- find_result(finish_table, 35, table_ZEC_USDT, ZEC, BTC, "ZEC->BTC->USD->ZEC", "ZEC->USD->BTC->ZEC", "BTC->ZEC->USD->BTC", "BTC->USD->ZEC->BTC")
  finish_table <- find_result(finish_table, 36, table_ZEC_ETH, ZEC, ETH, "ZEC->ETH->BTC->ZEC", "ZEC->BTC->ETH->ZEC", "ETH->ZEC->BTC->ETH", "ETH->BTC->ZEC->ETH")
  finish_table <- find_result(finish_table, 23, table_ZRX_USDT, ZRX, BTC, "ZRX->BTC->USD->ZRX", "ZRX->USD->BTC->ZRX", "BTC->ZRX->USD->BTC", "BTC->USD->ZRX->BTC")
  finish_table <- find_result(finish_table, 22, table_ZRX_ETH, ZRX, ETH, "ZRX->ETH->BTC->ZRX", "ZRX->BTC->ETH->ZRX", "ETH->ZRX->BTC->ETH", "ETH->BTC->ZRX->ETH")
  
  # ------------------
  return(finish_table)
}
